name: nesd
description: "NES emulator"
publish_to: 'none'

version: 0.13.0

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  archive: ^4.0.7
  auto_route: ^11.1.0
  binarize: ^2.0.0
  build_runner: ^2.5.4
  collection: ^1.19.1
  crypto: ^3.0.6
  es_compression: ^2.0.14
  ffi: ^2.1.4
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.4
  flutter_material_design_icons: ^1.1.7447
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  gamepads:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads
  hooks_riverpod: ^3.0.3
  image: ^4.5.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mp_audio_stream:
    git:
      url: https://github.com/jpjonte/mp-audio-stream.git
      ref: feature/buffer-size
  nesd_texture: any
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod: ^3.0.3
  riverpod_annotation: ^4.0.0
  riverpod_generator: ^4.0.0+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  xml: ^6.5.0

dev_dependencies:
  auto_route_generator: ^10.2.3
  custom_lint: ^0.8.0
  dart_code_metrics_presets: ^2.24.0
  flutter_test:
    sdk: flutter

  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lint: ^2.8.0
  mocktail: ^1.0.4
  riverpod_lint: ^3.0.3

dependency_overrides:
  gamepads_darwin:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_darwin
  gamepads_linux:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_linux
  gamepads_platform_interface:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_platform_interface
  gamepads_windows:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_windows

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
        - asset: assets/fonts/UbuntuMono-Italic.ttf
          style: italic
